# Generated by Django 5.0.3 on 2024-12-20 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0002_proveedor_ciudad'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matarial_compras',
            fields=[
                ('item', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=255)),
                ('unidad_manejo', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('secretaria_flag', models.BooleanField(default=False)),
                ('unidad_flag', models.BooleanField(default=False)),
                ('oficina_flag', models.BooleanField(default=False)),
                ('flag', models.BooleanField(default=True)),
                ('stock', models.FloatField(blank=True, default=0, null=True)),
                ('oficina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='usuarios.oficinas')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='proveedor.proveedor')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='usuarios.secretaria')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='usuarios.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_material_compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('costo_unitario', models.FloatField()),
                ('costo_total', models.FloatField(blank=True, null=True)),
                ('factura', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
                ('matarial_compras', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='material_compras.matarial_compras')),
            ],
        ),
    ]
