# Generated by Django 5.0.3 on 2024-12-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matarial_compras',
            fields=[
                ('item', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=255)),
                ('orden_compra', models.CharField(max_length=20)),
                ('numero_formulario', models.IntegerField(default=0)),
                ('unidad_manejo', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_compra', models.DateTimeField()),
                ('secretaria_flag', models.BooleanField(default=False)),
                ('unidad_flag', models.BooleanField(default=False)),
                ('oficina_flag', models.BooleanField(default=False)),
                ('flag', models.BooleanField(default=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('costo_unitario', models.FloatField(default=0)),
                ('costo_total', models.FloatField(blank=True, default=0, null=True)),
                ('factura', models.CharField(max_length=255)),
                ('estado_compra', models.CharField(default='PENDIENTE')),
            ],
        ),
        migrations.CreateModel(
            name='Numero_registro',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
