# Generated by Django 5.0.3 on 2024-12-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_material_compras',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock_material_compras',
            name='costo_total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock_material_compras',
            name='costo_unitario',
            field=models.FloatField(default=0),
        ),
    ]
