# Generated by Django 5.0.3 on 2024-12-20 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material_compras', '0002_alter_stock_material_compras_cantidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matarial_compras',
            old_name='stock',
            new_name='stock_compras',
        ),
    ]
