# Generated by Django 5.0.3 on 2025-02-14 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_compras', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido_compras',
            fields=[
                ('item', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_entrega', models.IntegerField(default=0)),
                ('estado_cardad', models.BooleanField()),
                ('fecha_cardista', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('material_comptras', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='material_compras.matarial_compras')),
            ],
        ),
    ]
