# Generated by Django 5.0.3 on 2025-02-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_compras', '0003_pedido_compras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido_compras',
            old_name='material_comptras',
            new_name='material_compras',
        ),
        migrations.RemoveField(
            model_name='pedido_compras',
            name='estado_cardad',
        ),
        migrations.AddField(
            model_name='pedido_compras',
            name='estado_cardista',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
