# Generated by Django 5.0.3 on 2024-12-20 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material_compras', '0003_rename_stock_matarial_compras_stock_compras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matarial_compras',
            old_name='stock_compras',
            new_name='stock',
        ),
    ]
