# Generated by Django 5.0.3 on 2024-12-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_compras', '0004_rename_stock_compras_matarial_compras_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matarial_compras',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
