# Generated by Django 5.0.3 on 2025-02-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_compras', '0004_rename_material_comptras_pedido_compras_material_compras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_compras',
            name='fecha_cardista',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
