# Generated by Django 5.0.3 on 2024-12-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_compras', '0005_alter_matarial_compras_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matarial_compras',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
