# Generated by Django 5.0.3 on 2024-09-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
