# Generated by Django 5.0.3 on 2024-09-19 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_proveedor_prue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='prue',
        ),
    ]
