# Generated by Django 5.0.3 on 2024-12-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizacion_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_autorizacion', models.BooleanField(default=False)),
                ('fecha_de_autorizacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_manejo', models.CharField(max_length=20)),
                ('numero_pedido', models.CharField(blank=True, null=True)),
                ('cantidad_pedida', models.IntegerField(default=0)),
                ('cantidad_entrega', models.IntegerField(blank=True, default=0, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('partida_presupuestada', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('costo_unidad', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('programa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sub_programa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proyecto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('act_u_obra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidad_ejecucion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('codigo_presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sub_cantidad_pedida', models.IntegerField(blank=True, default=0, null=True)),
                ('codigo_numero', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aprobado_unidad', models.BooleanField(blank=True, null=True)),
                ('aprobado_oficina', models.BooleanField(blank=True, null=True)),
                ('aprobado_presupuestos', models.BooleanField(blank=True, null=True)),
                ('aprobado_cardista', models.BooleanField(blank=True, null=True)),
                ('aprobado_almacen', models.BooleanField(blank=True, null=True)),
                ('aprobado_cardista_segunda', models.BooleanField(blank=True, null=True)),
                ('aprobado_cardista_segunda_fecha', models.DateTimeField(blank=True, null=True)),
                ('estado_pedido_almacen', models.CharField(default='Pendiente')),
                ('estado_de_pedido', models.CharField(default='pendiente')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega_salida', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
