# Generated by Django 5.0.3 on 2024-10-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='aprobado_presupuestos',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='aprobado_secretario',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
