# Generated by Django 5.0.3 on 2024-10-18 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_aprobado_presupuestos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='aprobado_secretario',
            new_name='aprobado_cardista',
        ),
    ]
