# Generated by Django 5.0.3 on 2024-11-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_aprobado_cardista_segunda_pedido_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='costo_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='costo_unidad',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='partida_presupuestada',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
