# Generated by Django 5.0.3 on 2024-08-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_alter_pedido_numero_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='aprobado_oficina',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
