# Generated by Django 5.0.3 on 2024-11-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion_material',
            name='precio_paquete',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio por paquetes'),
        ),
        migrations.AlterField(
            model_name='informacion_material',
            name='precio_unidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio por Unidad'),
        ),
    ]
