# Generated by Django 5.0.3 on 2025-02-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiales',
            name='precio_paquete',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materiales',
            name='precio_unidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
