# Generated by Django 5.0.3 on 2024-09-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='es_habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
