# Generated by Django 5.0.3 on 2024-09-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_factura_materiales_proveedor_materiales_factura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='nuemro_factural',
            new_name='nuemro_factura',
        ),
        migrations.AddField(
            model_name='factura',
            name='es_habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
