# Generated by Django 5.0.3 on 2024-09-18 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_categoria_es_habilitado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiales',
            name='cantidad_paquete',
        ),
        migrations.RemoveField(
            model_name='materiales',
            name='cantidad_paquete_unidad',
        ),
        migrations.RemoveField(
            model_name='materiales',
            name='precio_paquete',
        ),
        migrations.RemoveField(
            model_name='materiales',
            name='precio_unidad',
        ),
        migrations.RemoveField(
            model_name='materiales',
            name='total_precio',
        ),
    ]
