# Generated by Django 5.0.3 on 2024-10-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_materiales_gestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiales',
            name='unidad_manejo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Unidad de manejo'),
        ),
    ]
