# Generated by Django 5.0.3 on 2024-09-18 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0003_remove_materiales_cantidad_paquete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_paquete', models.IntegerField(verbose_name='Cantidad por paquetes')),
                ('cantidad_paquete_unidad', models.IntegerField(verbose_name='Cantidad por paquetes (en unidades)')),
                ('precio_paquete', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por paquetes')),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por Unidad')),
                ('total_precio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cantidad', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.materiales')),
            ],
        ),
    ]
