# Generated by Django 5.0.3 on 2024-09-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0004_rename_nuemro_factura_factura_codigo_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='codigo_factura',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
