# Generated by Django 5.0.3 on 2024-09-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0004_informacion_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion_material',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
