# Generated by Django 5.0.3 on 2024-10-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0004_materiales_cierre_gestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiales',
            name='gestion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
