# Generated by Django 5.0.3 on 2024-09-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0005_alter_informacion_material_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiales',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
