# Generated by Django 5.0.3 on 2024-10-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0006_alter_materiales_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiales',
            name='codigo_paquete',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Codigo de paquete'),
        ),
    ]
