# Generated by Django 5.0.3 on 2024-10-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0007_alter_materiales_codigo_paquete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiales',
            name='factura',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
