# Generated by Django 5.0.3 on 2024-08-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='encargado',
        ),
        migrations.AddField(
            model_name='usuario',
            name='encargado_oficina',
            field=models.BooleanField(choices=[(True, 'Encargado'), (False, 'Usuario')], default=False, verbose_name='Encargador de Oficina'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='encargado_unidad',
            field=models.BooleanField(choices=[(True, 'Encargado'), (False, 'Usuario')], default=False, verbose_name='Encargado de unidad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Super_administrador', 'Super administrador'), ('Axuliar', 'Axuliar'), ('Usuario', 'Usuario')], default='Personal', max_length=250),
        ),
    ]
