# Generated by Django 5.0.3 on 2024-08-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_encargado_usuario_encargado_oficina_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='encargado_oficina',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='encargado_unidad',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('Encargado_unidad', 'Encargado unidad'), ('Encargado_oficina', 'Encargado oficina'), ('Usuario', 'Usuario')], default='Usuario', verbose_name='Encargado de unidad'),
        ),
    ]
