# Generated by Django 5.0.3 on 2024-10-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='upload/', verbose_name='Imagen de perfil'),
        ),
    ]
