# Generated by Django 5.0.3 on 2024-10-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('Almacen', 'Almacen'), ('Secretario', 'Secretario'), ('Presupuestos', 'Presupuestos'), ('Director_administrativo', 'Director Administrativo'), ('Encargado_oficina', 'Responsable de la oficina'), ('Usuario', 'Personal de la oficina')], default='Usuario', verbose_name='Encargado de unidad'),
        ),
    ]
