# Generated by Django 5.0.3 on 2024-09-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_usuario_encargado_oficina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('Encargado_unidad', 'Inmedianto Superior'), ('Encargado_oficina', 'Responsable de la oficina'), ('Usuario', 'Personal de la oficina')], default='Usuario', verbose_name='Encargado de unidad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Super_administrador', 'Super administrador'), ('Auxiliar1', 'Auxiliar de Almacen'), ('Usuario', 'Usuario')], default='Personal', max_length=250),
        ),
    ]
