# Generated by Django 5.0.3 on 2024-10-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficinas',
            name='esHabilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='esHabilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='esHabilitado',
            field=models.BooleanField(default=True),
        ),
    ]
