# Generated by Django 5.0.3 on 2024-10-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_oficinas_eshabilitado_secretaria_eshabilitado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('Presupuestos', 'Presupuestos'), ('Cardista', 'Cardista'), ('Director_administrativo', 'Director Administrativo'), ('Encargado_oficina', 'Responsable de la oficina'), ('Usuario', 'Personal de la oficina')], default='Usuario', verbose_name='Encargado de unidad'),
        ),
    ]
